name: Code Quality

on:
  pull_request:
    branches: [main, develop]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install ESLint SARIF formatter
        run: npm install --no-save @microsoft/eslint-formatter-sarif

      - name: Run ESLint with annotations
        run: |
          npm run lint -- --format=@microsoft/eslint-formatter-sarif --output-file=eslint-results.sarif || true
        continue-on-error: true

      - name: Upload ESLint results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

      - name: Check for TODO comments
        run: |
          if grep -r "TODO\|FIXME\|XXX" --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" packages/; then
            echo "::warning::Found TODO/FIXME comments in code"
          fi

      - name: Check bundle size
        run: |
          npm run build
          echo "Bundle analysis would go here"

      - name: Security audit
        run: npm audit --audit-level=moderate

      - name: Check for unused dependencies
        run: npx depcheck || echo "::warning::Found unused dependencies"
